server: 
  port: 8082
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/eleMonitor?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate: 
        enable_lazy_load_no_trans: true
logging:
  file: ./logs/eleMonitor.log
  
management: 
  endpoints: 
    web: 
      exposure: 
        include: "*"
